# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Address-MobileJp
version:      0.08
version_from: lib/Mail/Address/MobileJp.pm
installdirs:  site
requires:
    Mail::Address:                 0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
